version: '3.6'
services:

  ######## Step 1. Get command from User ########

  # Get user text from HTTP GET requests
  user-request-listener_http-request:
    build: ./../../server_apps/user_request_handle/user-request-listener_http-request
    environment:
      MESSAGING_HOST: kafka
    ports:
      - 8080:8080
    restart: always

  ######## Step 2. Generate different variations for user command ########

  # Get user command text and send forward as is, without any changing
  text-option-provider_plain:
    build: ./../../server_apps/user_request_handle/text-option-provider_plain
    environment:
      MESSAGING_HOST: kafka
    restart: always

  ######## Step 3. Search the job by command ########

  # Get user command text and send forward as is, without any changing
  job-searcher_exact-match:
    build: ./../../server_apps/user_request_handle/job-searcher_exact-match
    environment:
      MESSAGING_HOST: kafka
    restart: always
